#!/bin/bash
## Configure the Codex CLI
#
# Everything Codex needs at create time lives here, so a devcontainer.json that lists
# "./features/codex" gets a working agent with NOTHING added to the project's own
# postcreate.sh. Declared as this feature's postCreateCommand in
# devcontainer-feature.json; the workspace folder is the cwd.
set -euo pipefail

TARGET=codex
SCRIPT_DIR=$(dirname "$0")
# .devcontainer/, two levels up from .devcontainer/features/codex/.
DEVCONTAINER_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# --- Persistent data volume ---
# A single Docker volume at ~/.data/ stores all agent data and shell history
# to survive container rebuilds. The volume mounts root-owned on first create; the
# chown is idempotent and every feature that touches ~/.data does it, since any of
# them may run first.
DATA="$HOME/.data"
sudo chown "$(id -u):$(id -g)" "$DATA"
mkdir -p "$DATA/$TARGET"

# --- Symlink agent data directories into the persistent volume ---
# If the volume directory is empty and the home directory has content from the feature
# installer, seed the volume with those files before symlinking.
vol_dir="$DATA/$TARGET"
home_dir="$HOME/.$TARGET"
if [ -d "$home_dir" ] && [ ! -L "$home_dir" ]; then
    if [ -z "$(ls -A "$vol_dir" 2>/dev/null)" ]; then
        cp -a "$home_dir/." "$vol_dir/"
    fi
    rm -rf "$home_dir"
fi
ln -sfn "$vol_dir" "$home_dir"

# --- Upgrade Codex ---
# Codex has no self-update subcommand, so re-running the feature's installer IS the
# upgrade path — single source of truth for both phases (it guards on `id -u`, so
# running it unprivileged from here is fine).
#
# This runs BEFORE the config generation below, not after, because the model catalog is
# generated from the installed binary and its per-model instruction templates change on
# every Codex release: generating from the outgoing binary would write a catalog that
# does not match the one Codex ends up running.
echo "Updating Codex CLI..."
bash "$SCRIPT_DIR/install.sh" || true

# --- Codex CLI config from the configured profiles ---
# Codex writes user choices (project trust, features, UI settings, plugin state) to
# ~/.codex/config.toml, so that file is left strictly user-owned — nothing here ever
# writes it. Generated provider defaults go to /etc/codex/config.toml, the
# lowest-precedence Codex layer, so a developer's own settings always win and the
# generated half can be replaced wholesale on every create.
#
# The aws profile targets OpenAI models via amazon-bedrock-runtime. awsgov uses
# amazon-bedrock with an explicit Mantle base_url, bypassing the automatic endpoint
# resolver's commercial-only Region list while retaining AWS SigV4 authentication.
# See the profiles' config.toml files and .claude/skills/profiles-and-spawn/SKILL.md.
# SEI profiles (opal, etc) aren't Bedrock. That per-profile opt-in is the whole point of generating
# this file rather than shipping a static one with the feature: a container whose
# profile has no Codex config must end up with NO config, not somebody else's.
#
# No merging: use the first configured profile that provides a config.toml.
DEVENV="$DEVCONTAINER_DIR/devcontainer.env"
PROFILES_DIR="$DEVCONTAINER_DIR/profiles"
CODEX_SYSTEM_CONFIG="/etc/codex/config.toml"

# Collected OUTSIDE the env-file guard so the removal path below still runs when there
# is no devcontainer.env at all — no configured profiles means no generated config,
# however that state was reached.
CODEX_FILES=()
if [ -f "$DEVENV" ]; then
    PROFILES_LINE=$(grep '^CONFIGURED_PROFILES=' "$DEVENV" 2>/dev/null || true)
    if [ -n "$PROFILES_LINE" ]; then
        CSV="${PROFILES_LINE#CONFIGURED_PROFILES=}"
        # Strip CR before splitting — load-bearing on Windows hosts, where setup.ps1
        # writes devcontainer.env with CRLF and we read the file DIRECTLY (Docker's
        # --env-file trims for us, this path does not). Without it the LAST profile in
        # the CSV keeps a trailing \r and every path built from it misses, silently.
        # Full story in features/chat/postcreate.sh, where the bug first surfaced.
        CSV="${CSV//$'\r'/}"
        IFS=',' read -ra CONFIGURED <<< "$CSV"

        for profile in "${CONFIGURED[@]}"; do
            if [ -f "$PROFILES_DIR/$profile/config.toml" ]; then
                CODEX_FILES+=("$profile")
            fi
        done
    fi
fi

if [ ${#CODEX_FILES[@]} -ge 1 ]; then
    sudo mkdir -p "$(dirname "$CODEX_SYSTEM_CONFIG")"
    {
        echo "# Generated by .devcontainer/features/codex/postcreate.sh from configured profiles."
        echo "# User-specific Codex settings belong in ~/.codex/config.toml."
        echo ""
        cat "$PROFILES_DIR/${CODEX_FILES[0]}/config.toml"
    } | sudo tee "$CODEX_SYSTEM_CONFIG" >/dev/null
# Remove OUR generated file when no configured profile provides one (a profile switch,
# or aws dropped), but never a hand-written one. The guard matches the marker loosely
# (any .devcontainer/ path) so a file generated by the earlier owner of this logic —
# .devcontainer/postcreate.sh — is still recognised and cleaned up.
elif [ -f "$CODEX_SYSTEM_CONFIG" ] && grep -q '^# Generated by \.devcontainer/' "$CODEX_SYSTEM_CONFIG"; then
    sudo rm -f "$CODEX_SYSTEM_CONFIG"
fi

# --- Codex model picker: keep the profile's usable models ---
# Bedrock Runtime lists every OpenAI model twice, once per cross-region inference
# profile (global.openai.* and us.openai.*). model_catalog_json replaces Codex's
# built-in catalog with a file, letting aws keep only the `us.` half and add
# GPT-6 Sol/Luna while upstream's Bedrock catalog catches up (model-catalog.jq).
# GovCloud keeps GPT-5.6 Terra and Luna on
# Mantle in west; its stock catalog also offers models that return 404 there.
#
# It must be GENERATED, not tracked: a catalog entry REPLACES the built-in one and Codex
# rejects a partial entry (`missing field display_name`), so the file has to carry every
# field — including the per-model instruction templates, which change on each Codex
# release. Regenerating from the installed binary (upgraded above) keeps it in step.
#
# A model_catalog_json path that does not exist is a FATAL config error ("Error: No such
# file or directory") that bricks every codex invocation, so the profile config.toml
# deliberately does not name it: the key is prepended here only after the file is
# successfully written. Warn-only on failure — this script runs under `set -euo pipefail`
# and a stale or missing catalog must never cost the create.
#
# Resolve the binary by path as well as PATH: a feature postCreateCommand is not
# guaranteed a login shell, so ~/.local/bin (where the installer puts codex) may be
# absent from PATH even though the upgrade above succeeded.
CODEX_BIN="$(command -v codex 2>/dev/null || true)"
if [ -z "$CODEX_BIN" ] && [ -x "$HOME/.local/bin/codex" ]; then
    CODEX_BIN="$HOME/.local/bin/codex"
fi

CODEX_CATALOG="/etc/codex/model-catalog.json"
if [ ${#CODEX_FILES[@]} -ge 1 ] && [ -n "$CODEX_BIN" ]; then
    CODEX_PROVIDER="$(sed -n 's/^model_provider = "\(.*\)"$/\1/p' "$PROFILES_DIR/${CODEX_FILES[0]}/config.toml")"
    CODEX_DEFAULT_MODEL="$(sed -n 's/^model = "\(.*\)"$/\1/p' "$PROFILES_DIR/${CODEX_FILES[0]}/config.toml")"
    CODEX_CATALOG_TMP="$(mktemp)"
    # Explicit provider: a stale user-level provider must not generate the other
    # partition's catalog. The system config above has no catalog key yet.
    if timeout 60 "$CODEX_BIN" debug models -c "model_provider=\"$CODEX_PROVIDER\"" 2>/dev/null \
        | jq --arg profile "${CODEX_FILES[0]}" -f "$SCRIPT_DIR/model-catalog.jq" \
        > "$CODEX_CATALOG_TMP" 2>/dev/null \
        && [ -s "$CODEX_CATALOG_TMP" ] \
        && jq -e --arg model "$CODEX_DEFAULT_MODEL" \
            'any(.models[]; .slug == $model)' "$CODEX_CATALOG_TMP" >/dev/null 2>&1; then
        sudo install -m 644 "$CODEX_CATALOG_TMP" "$CODEX_CATALOG"
        # A profile can end in a [model_providers.*] table. Appending would put
        # model_catalog_json inside that table, where Codex rejects it.
        {
            echo "model_catalog_json = \"$CODEX_CATALOG\""
            cat "$CODEX_SYSTEM_CONFIG"
        } > "$CODEX_CATALOG_TMP"
        sudo install -m 644 "$CODEX_CATALOG_TMP" "$CODEX_SYSTEM_CONFIG"
    else
        # Leave the key out entirely rather than point at a missing file.
        echo -e "\e[33m⚠️  Could not generate the Codex model catalog; the /model picker will\e[0m"
        echo -e "\e[33m   use the stock list, which may include unavailable or duplicate models.\e[0m"
        sudo rm -f "$CODEX_CATALOG"
    fi
    rm -f "$CODEX_CATALOG_TMP"
elif [ -f "$CODEX_CATALOG" ]; then
    # No Codex profile config any more — drop the file we generated.
    sudo rm -f "$CODEX_CATALOG"
fi

# --- Warn when the user layer shadows the profile ---
# The USER layer wins over the system layer, and an older postcreate wrote the profile
# config there. A leftover model/model_provider from that era silently shadows every
# profile change (seen live: a stale amazon-bedrock + openai.gpt-5.6-sol kept Codex on
# Mantle long after the profile moved to amazon-bedrock-runtime). Warn only — the file is
# the user's; never edit it from here.
CODEX_USER_CONFIG="$HOME/.codex/config.toml"
CODEX_SHADOW_RE='^[[:space:]]*(model|model_provider)[[:space:]]*=|^[[:space:]]*\[model_providers\.'
if [ ${#CODEX_FILES[@]} -ge 1 ] && [ -f "$CODEX_USER_CONFIG" ] \
    && grep -qE "$CODEX_SHADOW_RE" "$CODEX_USER_CONFIG"; then
    echo ""
    echo -e "\e[33m⚠️  ~/.codex/config.toml sets its own model/provider, which overrides the\e[0m"
    echo -e "\e[33m   profile config in $CODEX_SYSTEM_CONFIG:\e[0m"
    grep -nE "$CODEX_SHADOW_RE" "$CODEX_USER_CONFIG" | sed 's/^/     /' || true
    echo "   Remove those lines from ~/.codex/config.toml to follow the profile."
    echo ""
fi
