// Copyright 2017 Carnegie Mellon University. All Rights Reserved. See LICENSE.md file for terms.

using System.Text.Json.Nodes;
using Ghosts.Api.Infrastructure.ScenarioDocuments;
using Xunit.Abstractions;

namespace Ghosts.Api.Tests;

/// <summary>
/// The validator against the schema's own examples and against a corpus of documents with one planted
/// defect each. No database: tiers 1 and 2 read a document and nothing else.
/// </summary>
public class ScenarioDocumentValidatorTests(ITestOutputHelper output)
{
    /// <summary>
    /// The examples must be clean, with named exceptions and no others. Both exceptions are true
    /// statements about the RPG fixture the example was converted from, and the example says what its
    /// fixture says rather than being bent to fit: soc-morning and meridian-hybrid declare a sub-hour
    /// exercise that GHOSTS cannot store (duration_hours is an integer), and soc-morning also schedules
    /// an event at T+60m inside a 45-minute exercise, which was wrong in the fixture before any of this
    /// existed. Listing them per file rather than allowing a code everywhere keeps the assertion tight.
    /// </summary>
    [Theory]
    [InlineData("meridian-hybrid.scenario.json", "TIME_DURATION_NOT_STORABLE")]
    [InlineData("operation-overlord.scenario.json", "")]
    [InlineData("phishing-drill.scenario.json", "")]
    [InlineData("soc-morning.scenario.json", "TIME_DURATION_NOT_STORABLE,TIME_OUTSIDE_DURATION")]
    public void Example_documents_have_no_errors(string file, string allowedErrorCodes)
    {
        var result = ScenarioDocumentValidator.Validate(Load(Path.Combine(Schemas, "examples", file)));

        foreach (var finding in result.Findings)
            output.WriteLine($"{finding.Severity,-7} {finding.Code,-28} {finding.Path} — {finding.Message}");

        var allowed = allowedErrorCodes.Split(',', StringSplitOptions.RemoveEmptyEntries).ToHashSet();
        var errors = result.Findings.Where(f => f.Severity == ScenarioFinding.Error).ToList();

        Assert.DoesNotContain(errors, f => !allowed.Contains(f.Code));
        Assert.All(allowed, code => Assert.Contains(errors, f => f.Code == code));
    }

    /// <summary>
    /// Tier 1 must agree with ajv, which is the schema's reference implementation and the one the
    /// node tooling uses. crosscheck-expected.json is ajv's verdict and failing paths, regenerated by
    /// test.sh, so neither validator can drift without the other noticing.
    /// </summary>
    [Fact]
    public void Tier_1_agrees_with_ajv()
    {
        var expected = JsonNode.Parse(File.ReadAllText(Path.Combine(Schemas, "tests", "crosscheck-expected.json")))!
            .AsObject();

        foreach (var (file, want) in expected)
        {
            var path = Directory.GetFiles(Schemas, file, SearchOption.AllDirectories).Single();
            var result = ScenarioDocumentValidator.Validate(Load(path));

            // Tier 1 stops the run before tier 2, so a document with schema errors reports only them.
            var tier1 = result.Findings.Where(f => f.Tier == 1).ToList();
            var got = tier1.Select(f => f.Path.Length == 0 ? "/" : f.Path).Distinct().OrderBy(p => p, StringComparer.Ordinal).ToList();
            var wantPaths = want!["paths"]!.AsArray().Select(p => p!.GetValue<string>()).ToList();

            output.WriteLine($"{file}: ajv {(want["valid"]!.GetValue<bool>() ? "valid" : "invalid")}, .NET {tier1.Count} finding(s)");
            foreach (var finding in tier1) output.WriteLine($"  {finding.Code,-30} {finding.Path} — {finding.Message}");

            Assert.Equal(want["valid"]!.GetValue<bool>(), tier1.Count == 0);
            Assert.Equal(wantPaths, got);
        }
    }

    /// <summary>
    /// One document per tier-2 check, each with exactly one planted defect. The file name says which
    /// code and which pointer it must produce: <c>CODE__pointer-with-dashes.json</c>, described in
    /// the directory's README.
    /// </summary>
    [Theory]
    [MemberData(nameof(Tier2Cases))]
    public void Tier_2_finds_the_planted_defect(string file)
    {
        var expected = JsonNode.Parse(File.ReadAllText(Path.Combine(Tier2, "expected.json")))!.AsObject()[file]!;
        var code = expected["code"]!.GetValue<string>();
        var path = expected["path"]!.GetValue<string>();
        var severity = expected["severity"]?.GetValue<string>() ?? ScenarioFinding.Error;

        var result = ScenarioDocumentValidator.Validate(Load(Path.Combine(Tier2, file)));
        foreach (var finding in result.Findings)
            output.WriteLine($"{finding.Severity,-7} {finding.Code,-28} {finding.Path} — {finding.Message}");

        Assert.Contains(result.Findings, f => f.Code == code && f.Path == path && f.Severity == severity);

        // Nothing else at error severity: a planted defect must not be found by producing a second one.
        var others = result.Findings
            .Where(f => f.Severity == ScenarioFinding.Error && !(f.Code == code && f.Path == path))
            .ToList();
        Assert.Empty(others);
    }

    public static TheoryData<string> Tier2Cases()
    {
        var data = new TheoryData<string>();
        foreach (var file in Directory.GetFiles(Tier2, "*.json").OrderBy(f => f, StringComparer.Ordinal))
        {
            var name = Path.GetFileName(file);
            if (name != "expected.json") data.Add(name);
        }
        return data;
    }

    // ───────── mapper: canonical form and the duration that cannot be stored ─────────

    [Fact]
    public void Canonical_form_omits_schema_defaults()
    {
        var document = JsonNode.Parse("""
            {
              "schemaVersion": "1.1.0", "slug": "d", "name": "D", "description": "d",
              "edges": [{ "from": "a", "to": "b", "type": "Uses", "weight": 1 }],
              "entities": [
                { "id": "a", "name": "A", "type": "Person",
                  "provenance": { "origin": "operator", "confidence": 1, "reviewed": false } },
                { "id": "b", "name": "B", "type": "Person",
                  "provenance": { "origin": "extracted", "confidence": 0.5, "reviewed": false } }
              ]
            }
            """)!;

        var text = ScenarioDocumentMapper.Serialize(document);

        Assert.DoesNotContain("weight", text);
        Assert.DoesNotContain("reviewed", text);
        Assert.DoesNotContain("\"operator\"", text);   // the default origin
        Assert.Contains("\"extracted\"", text);        // not the default, so it stays
        Assert.Contains("0.5", text);
        Assert.EndsWith("}\n", text);
    }

    [Theory]
    [InlineData("11d", true, 264)]
    [InlineData("2h", true, 2)]
    [InlineData("1h30m", false, 0)]
    [InlineData("45m", false, 0)]
    public void A_duration_is_storable_only_in_whole_hours(string duration, bool storable, int hours)
    {
        Assert.Equal(storable, ScenarioDocumentMapper.TryDurationHours(duration, out var got));
        Assert.Equal(hours, got);
    }

    [Fact]
    public void A_duration_that_cannot_be_stored_blocks_the_import()
    {
        var document = Load(Path.Combine(Tier2, "TIME_DURATION_NOT_STORABLE__rulesOfPlay-duration.json"));
        var result = ScenarioDocumentValidator.Validate(document);

        Assert.False(result.IsValid);
        // And the mapper refuses rather than rounding, in case the validator is ever skipped.
        Assert.Throws<InvalidOperationException>(() => ScenarioDocumentMapper.FromDocument(document));
    }

    // ───────── locating the schema tree from the test binary ─────────

    private static readonly string Schemas = Find();
    private static string Tier2 => Path.Combine(Schemas, "tests", "tier2");

    private static JsonObject Load(string path) => JsonNode.Parse(File.ReadAllText(path))!.AsObject();

    private static string Find()
    {
        for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir != null; dir = dir.Parent)
        {
            var candidate = Path.Combine(dir.FullName, "schemas", "scenario-document");
            if (Directory.Exists(candidate)) return candidate;
        }
        throw new DirectoryNotFoundException("schemas/scenario-document is not above the test binary");
    }
}
