taskkill /im "ghosts.exe" /F
taskkill /im "geckodriver.exe" /F
taskkill /im "firefox.exe" /F
taskkill /im "chromedriver.exe" /F
taskkill /im "chrome.exe" /F
taskkill /im "outlook.exe" /F
taskkill /im "winword.exe" /F
taskkill /im "powerpnt.exe" /F
taskkill /im "excel.exe" /F
taskkill /im "crashreporter.exe" /F