#!/bin/bash
## Configure Grok Build (the `grok` CLI)
#
# Everything Grok needs at create time lives here, so a devcontainer.json that lists
# "./features/grok" gets a working agent with NOTHING added to the project's own
# postcreate.sh. Declared as this feature's postCreateCommand in
# devcontainer-feature.json; the workspace folder is the cwd.
set -euo pipefail

TARGET=grok
SCRIPT_DIR=$(dirname "$0")
# .devcontainer/, two levels up from .devcontainer/features/grok/.
DEVCONTAINER_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# --- Persistent data volume ---
# A single Docker volume at ~/.data/ stores all agent data and shell history
# to survive container rebuilds. The volume mounts root-owned on first create; the
# chown is idempotent and every feature that touches ~/.data does it, since any of
# them may run first.
DATA="$HOME/.data"
sudo chown "$(id -u):$(id -g)" "$DATA"
mkdir -p "$DATA/$TARGET"

# --- Symlink agent data directories into the persistent volume ---
# If the volume directory is empty and the home directory has content from the feature
# installer, seed the volume with those files before symlinking.
#
# ~/.grok holds more than state: the installer keeps the grok BINARY there too
# (~/.grok/downloads, linked from ~/.grok/bin and ~/.local/bin). So on a first create the
# seed copy is what puts the binary on the volume, and on every later create the image's
# freshly built copy is discarded here like any other home-dir content. That is why
# `grok update` runs at the END of this script rather than before the link (where the
# old inline version in scripts/postcreate.sh had it): after the link it upgrades the
# volume's copy — the one that survives — instead of the image copy about to be thrown
# away. ~/.local/bin/grok comes from the image and points at $HOME/.grok/bin/grok, so it
# resolves through the symlink either way.
vol_dir="$DATA/$TARGET"
home_dir="$HOME/.$TARGET"
if [ -d "$home_dir" ] && [ ! -L "$home_dir" ]; then
    if [ -z "$(ls -A "$vol_dir" 2>/dev/null)" ]; then
        cp -a "$home_dir/." "$vol_dir/"
    fi
    rm -rf "$home_dir"
fi
ln -sfn "$vol_dir" "$home_dir"

# --- Grok config from the configured profiles ---
# Grok reads /etc/grok/managed_config.toml as fleet defaults that the user's own
# ~/.grok/config.toml overrides — the analogue of Codex's /etc/codex/config.toml, kept
# system-level for the same reason: ~/.grok/config.toml is user-owned (the installer
# records its update channel there, /settings writes there) and sits on the persisted
# volume, so generated content there would go stale and shadow later profile changes.
#
# Each profile's grok.toml fragment holds ONLY [auth_provider.<name>] and
# [model."<profile>/<name>"] tables, so fragments concatenate into valid TOML; the single
# [models] table is emitted here — `default` is the first model key, `allowed_models` is
# every key. The allowlist hides Grok's built-in xAI-hosted grok-4.x entries, which need a
# `grok login`/XAI_API_KEY and would send code to x.ai — the same reason every OpenCode
# profile disables its bundled Zen provider. Telemetry is off for the same data-boundary
# reason. A user can lift either in ~/.grok/config.toml (user layer wins).
DEVENV="$DEVCONTAINER_DIR/devcontainer.env"
PROFILES_DIR="$DEVCONTAINER_DIR/profiles"
GROK_MANAGED_CONFIG="/etc/grok/managed_config.toml"

# Collected OUTSIDE the env-file guard so the removal path below still runs when there
# is no devcontainer.env at all — no configured profiles means no generated config,
# however that state was reached.
GROK_FILES=()
if [ -f "$DEVENV" ]; then
    PROFILES_LINE=$(grep '^CONFIGURED_PROFILES=' "$DEVENV" 2>/dev/null || true)
    if [ -n "$PROFILES_LINE" ]; then
        CSV="${PROFILES_LINE#CONFIGURED_PROFILES=}"
        # Strip CR before splitting — load-bearing on Windows hosts, where setup.ps1
        # writes devcontainer.env with CRLF and we read the file DIRECTLY (Docker's
        # --env-file trims for us, this path does not). Without it the LAST profile in
        # the CSV keeps a trailing \r and every path built from it misses, silently.
        # Full story in features/chat/postcreate.sh, where the bug first surfaced.
        CSV="${CSV//$'\r'/}"
        IFS=',' read -ra CONFIGURED <<< "$CSV"

        for profile in "${CONFIGURED[@]}"; do
            if [ -f "$PROFILES_DIR/$profile/grok.toml" ]; then
                GROK_FILES+=("$profile")
            fi
        done
    fi
fi

if [ ${#GROK_FILES[@]} -ge 1 ]; then
    GROK_PATHS=()
    for p in "${GROK_FILES[@]}"; do GROK_PATHS+=("$PROFILES_DIR/$p/grok.toml"); done
    # Model keys in declaration order: [model."aws/grok-4.6"] -> aws/grok-4.6
    mapfile -t GROK_KEYS < <(sed -n 's/^\[model\."\([^"]*\)"\]$/\1/p' "${GROK_PATHS[@]}")
    sudo mkdir -p "$(dirname "$GROK_MANAGED_CONFIG")"
    {
        echo "# Generated by .devcontainer/features/grok/postcreate.sh from configured profiles."
        echo "# User-specific Grok settings belong in ~/.grok/config.toml, which overrides this file."
        if [ ${#GROK_KEYS[@]} -ge 1 ]; then
            GROK_ALLOWED=$(printf '"%s", ' "${GROK_KEYS[@]}")
            echo ""
            echo "[models]"
            echo "default = \"${GROK_KEYS[0]}\""
            echo "allowed_models = [${GROK_ALLOWED%, }]"
        fi
        echo ""
        echo "[features]"
        echo "telemetry = false"
        for f in "${GROK_PATHS[@]}"; do echo ""; cat "$f"; done
    } | sudo tee "$GROK_MANAGED_CONFIG" >/dev/null
# Remove OUR generated file when no configured profile provides one (a profile switch, or
# the Bedrock profiles dropped), but never a hand-written one. The guard matches the
# marker loosely (any .devcontainer/ path) so a file generated by the earlier owner of
# this logic — .devcontainer/scripts/postcreate.sh — is still recognised and cleaned up.
elif [ -f "$GROK_MANAGED_CONFIG" ] && grep -q '^# Generated by \.devcontainer/' "$GROK_MANAGED_CONFIG"; then
    sudo rm -f "$GROK_MANAGED_CONFIG"
fi

# Update to the latest version (runs on every create, bypassing the image cache).
# Deliberately after the volume link — see the note above.
echo "Updating Grok Build..."
grok update || true
