# docker-compose up -d
# -f compose-api.yml (if you want a custom file)

version: '3.2'
networks:
  ghosts-network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: ghosts-postgres
    environment:
      POSTGRES_DB: ghosts
      POSTGRES_USER: ghosts
      POSTGRES_PASSWORD: scotty@1
    volumes:
      - /Users/dustin/data/ghosts/db_data:/var/lib/postgresql/data
      - /Users/dustin/data/ghosts/spectre_data:/tmp
    logging:
      options:
        max-size: '100m'
        max-file: '5'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ghosts']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ghosts-network
    restart: always

  ghosts-api:
    image: dustinupdyke/ghosts
    container_name: ghosts-api
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    networks:
      - ghosts-network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: ghosts-grafana
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - ghosts-network
    restart: always
    volumes:
      - /Users/dustin/data/ghosts/g_data:/var/lib/grafana