# Copyright 2017 Carnegie Mellon University. All Rights Reserved. See LICENSE.md file for terms.

FROM mcr.microsoft.com/dotnet/core/sdk:latest AS build

# copy csproj and restore as distinct layers
COPY ghosts.api.sln ./app/
COPY Ghosts.Api/*csproj ./app/Ghosts.Api/
COPY Ghosts.Domain/*csproj ./app/Ghosts.Domain/
COPY Ghosts.Domain/*.config ./app/Ghosts.Domain/
WORKDIR /app
RUN dotnet restore

# copy everything else and build app
COPY Ghosts.Api/     ./Ghosts.Api/
COPY Ghosts.Domain/     ./Ghosts.Domain/
WORKDIR /app/Ghosts.Api/
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:latest
COPY --from=build /app/Ghosts.Api/out ./app

WORKDIR /app

ENV GHOSTS_VERSION=3.0.0.0
ENV GHOSTS_API_VERSION=v2
ENV ASPNETCORE_URLS=http://*:5000

EXPOSE 5000

CMD ["dotnet", "ghosts.api.dll"]
