# docker-compose up -d
# -f compose-api.yml (if you want a custom file)

version: "3.2"
networks:
  ghosts-network:
    driver: bridge
services:
  postgres:
    image: postgres:12-alpine
    container_name: ghosts-postgres
    environment:
      POSTGRES_DB: ghosts
      POSTGRES_USER: ghosts
      POSTGRES_PASSWORD: scotty@1
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ghosts"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ghosts-network
    restart: always

  ghosts-api:
    build:
      context: ..
      dockerfile: Ghosts.Api/dockerfile
    container_name: ghosts-api
    depends_on:
      - postgres
    environment:
      - ConnectionStrings:DefaultConnection=Host=ghosts-postgres;Port=5432;Database=ghosts;User Id=ghosts;Password=scotty@1;
    ports:
      - "5000:5000"
    networks:
      - ghosts-network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: ghosts-grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - ghosts-network
    restart: always
