"use client";

import { JSONImporter } from "@/components/json-utils";
import AutoForm, { AutoFormSubmit } from "@/components/ui/auto-form";
import { api, schemas } from "@/generated/endpoints";
import { useApiCall } from "@/lib/utils";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { z } from "zod";

/**
 * This form is autogenerated using @see https://github.com/vantezzen/auto-form
 * The NPC object has so many fields, manually creating a form is unreasonable.
 */
export function NpcForm() {
	const router = useRouter();
	const [values, setValues] = useState<z.infer<typeof schemas.NpcProfile>>({});
	const call = useApiCall();
	return (
		<>
			<JSONImporter
				validator={schemas.NpcProfile}
				onValidData={(data) => setValues(data)}
			/>
			<AutoForm
				values={values}
				onValuesChange={setValues}
				formSchema={schemas.NpcProfile}
				onSubmit={async (data) => {
					await call(api.postApinpcs(data), "Created NPC");
					router.push("/npcs");
					router.refresh();
				}}
			>
				<AutoFormSubmit>Create</AutoFormSubmit>
			</AutoForm>
		</>
	);
}
