# Dev container first-run setup (Windows hosts).
# Called by .devcontainer/init.cmd when devcontainer.env is missing.
# Generates a minimal env file so the container can start; the file is
# gitignored, so fill in your own credentials/models afterward.
$ErrorActionPreference = 'Stop'

$envFile = Join-Path $PSScriptRoot 'devcontainer.env'

if (Test-Path $envFile) { exit 0 }

@'
# Auto-generated by .devcontainer/setup.ps1 on first run.
# This file is gitignored. Edit it to add credentials/models for your setup.
CONFIGURED_PROFILES=
START_SERVICES=false
'@ | Set-Content -NoNewline -Path $envFile -Encoding ascii

Write-Host "Created default .devcontainer/devcontainer.env"
