#!/bin/bash
# Dev container first-run setup (POSIX hosts).
# Called by .devcontainer/init when devcontainer.env is missing.
# Generates a minimal env file so the container can start; the file is
# gitignored, so fill in your own credentials/models afterward.
set -euo pipefail

ENV_FILE="$(dirname "$0")/devcontainer.env"

[ -f "$ENV_FILE" ] && exit 0

cat > "$ENV_FILE" <<'EOF'
# Auto-generated by .devcontainer/setup.sh on first run.
# This file is gitignored. Edit it to add credentials/models for your setup.
CONFIGURED_PROFILES=
START_SERVICES=false
EOF

echo "Created default .devcontainer/devcontainer.env"
