{
 "title": "GHOSTS GROUP",
 "time": { "from": "2018-09-18T02:16:01.130Z", "to": "2018-09-18T14:16:01.130Z" },
 "templating": {
  "list": [
   { "name": "group_id", "query": "3" }
  ]
 },
 "panels": [
  {
   "title": "NPCs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM machines m, groups g, group_machines gm WHERE m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id;"
    }
   ]
  },
  {
   "title": "ACTIVITIES",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM history_timeline h, machines m, group_machines gm, groups g WHERE h.machineid = m.id and m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id;"
    }
   ]
  },
  {
   "title": "POLLING",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM history_machine h, machines m, group_machines gm, groups g WHERE h.machineid = m.id and m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id;"
    }
   ]
  },
  {
   "title": "HEALTH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM history_health h, machines m, group_machines gm, groups g WHERE h.machineid = m.id and m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id;"
    }
   ]
  },
  {
   "title": "ALL ACTIVITIES",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(h.createdutc, '5m', 0),\n  count(h.*) as \"Timeline\"\nFROM\n  history_timeline h, machines m, group_machines gm, groups g\nWHERE \n  h.machineid = m.id and m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id and $__timeFilter(h.createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(h.createdutc, '5m', 0),\n  count(h.*) as \"Health\"\nFROM\n  history_health h, machines m, group_machines gm, groups g\nWHERE \n  h.machineid = m.id and m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id and $__timeFilter(h.createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(h.createdutc, '5m', 0),\n  count(h.*) as \"Polls\"\nFROM\n  history_machine h, machines m, group_machines gm, groups g\nWHERE \n  h.machineid = m.id and m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id and $__timeFilter(h.createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    }
   ]
  },
  {
   "title": "TIMELINE BREAKDOWN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  handler as \"Handler\",\n  count(*) as \"Executions\",\n  date_trunc('minute', h.createdutc) as \"time\"\nFROM\n  history_timeline h, machines m, group_machines gm, groups g\nWHERE \n  h.machineid = m.id and m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id and $__timeFilter(h.createdutc)\ngroup by h.handler, date_trunc('minute', h.createdutc) \norder by date_trunc('minute', h.createdutc)  DESC\n"
    }
   ]
  },
  {
   "title": "TIMELINE TOTALS",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT h.handler as \"Handler\", count(h.*) as \"Executions\" from history_timeline h, machines m, group_machines gm, groups g\nWHERE \n  h.machineid = m.id and m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id group by handler;"
    }
   ]
  },
  {
   "title": "LAST REPORTING",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT m.name as \"Machine\", 'Up' as \"Status\", m.lastreportedutc as \"Time\" from machines m, group_machines gm, groups g\nWHERE \n  m.id = gm.machineid and gm.groupid = g.id and g.id = $group_id\norder by m.lastreportedutc desc limit 8;"
    }
   ]
  }
 ]
}