{
 "title": "GHOSTS",
 "time": { "from": "2018-09-18T02:16:01.130Z", "to": "2018-09-18T14:16:01.130Z" },
 "panels": [
  {
   "title": "NPCs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM machines;" }
   ]
  },
  {
   "title": "ACTIVITIES",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM historytimeline;"
    }
   ]
  },
  {
   "title": "POLLING",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM historymachine;"
    }
   ]
  },
  {
   "title": "HEALTH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM historyhealth;"
    }
   ]
  },
  {
   "title": "ALL ACTIVITIES",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(createdutc, '5m', 0),\n  count(*) as \"Timeline\"\nFROM\n  historytimeline\nWHERE \n  $__timeFilter(createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(createdutc, '5m', 0),\n  count(*) as \"Health\"\nFROM\n  historyhealth\nWHERE \n  $__timeFilter(createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(createdutc, '5m', 0),\n  count(*) as \"Polls\"\nFROM\n  historymachine\nWHERE \n  $__timeFilter(createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    }
   ]
  },
  {
   "title": "TIMELINE BREAKDOWN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  handler as \"Handler\",\n  count(*) as \"Executions\",\n  date_trunc('minute', createdutc) as \"time\"\nFROM\n  historytimeline\ngroup by handler, date_trunc('minute', createdutc) \norder by date_trunc('minute', createdutc)  DESC\n"
    }
   ]
  },
  {
   "title": "TIMELINE TOTALS",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT handler as \"Handler\", count(*) as \"Executions\" from historytimeline group by handler;"
    }
   ]
  },
  {
   "title": "LAST REPORTING",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT name as \"Machine\", 'Up' as \"Status\", lastreportedutc as \"Time\" from machines order by lastreportedutc desc limit 8;"
    }
   ]
  }
 ]
}