FROM mcr.microsoft.com/dotnet/core/sdk:latest AS build

# copy csproj and restore as distinct layers
COPY ghosts.linux.sln ./app/
COPY ghosts.client.linux/*csproj ./app/ghosts.client.linux/
COPY Ghosts.Domain/*csproj ./app/Ghosts.Domain/
COPY Ghosts.Domain/*.config ./app/Ghosts.Domain/

WORKDIR /app
RUN dotnet restore

# copy everything else and build app
COPY ghosts.client.linux/     ./ghosts.client.linux/
COPY Ghosts.Domain/     ./Ghosts.Domain/
WORKDIR /app/ghosts.client.linux/
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine

# Install ASP.NET Core
RUN aspnetcore_version=3.1.4 \
    && wget -O aspnetcore.tar.gz https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/$aspnetcore_version/aspnetcore-runtime-$aspnetcore_version-linux-musl-x64.tar.gz \
    && aspnetcore_sha512='f60e9226a5b399470479fd6fdebd03442b0440128be1090adcbe473dba46a3e7a57a9e59b4abff96214e0dd0b1123c67fe764b74c61de1cb35c8b8ac45767eb9' \
    && echo "$aspnetcore_sha512  aspnetcore.tar.gz" | sha512sum -c - \
    && tar -ozxf aspnetcore.tar.gz -C /usr/share/dotnet ./shared/Microsoft.AspNetCore.App \
    && rm aspnetcore.tar.gz

RUN apk add curl && \
    apk add nmap && \
    apk add busybox-extras && \
    apk add nikto && \
    apk add openssh-client && \
    apk add openssh-keygen && \
    apk add python && \
    wget 'https://github.com/sqlmapproject/sqlmap/tarball/master' --output-document=sqlmap.tar.gz && \
    mkdir sqlmap && \
    tar -xvf sqlmap.tar.gz -C sqlmap && \
    cd sqlmap/
# python sqlmap.py --version

COPY --from=build /app/ghosts.client.linux/out ./app
WORKDIR /app/  

ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000/tcp

CMD ["dotnet", "./ghosts.client.linux.dll"]
