FROM booyaabes/kali-linux-full:latest

# install dotnetcore
RUN sudo apt-get --assume-yes install -y gpg && \
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg && \
    sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/ && \
    wget -q https://packages.microsoft.com/config/ubuntu/19.04/prod.list && \
    sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list && \
    sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg && \
    sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list && \
    apt-get update && \
    sudo apt-get --assume-yes install -y apt-transport-https && \
    sudo apt-get update && \
    sudo apt-get --assume-yes install aspnetcore-runtime-3.1

WORKDIR /opt/ghosts  
COPY  bin/publish .
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000/tcp

# if we wanted to do other commands at startup in the future
# CMD [ "/usr/local/bin/start.sh" ] 

CMD ["dotnet", "./ghosts.client.linux.dll"]



# dotnet publish -c Release -o bin/publish
# docker build . -f dockerfile-kali -t ghosts/staypuft

# docker swarm init
# docker stack deploy ghosts-staypuft --compose-file docker-compose.yml
# Docker swarm leave --force

# docker run -d -p 7000:5000 --name ghosts-staypuft ghosts/staypuft
