# dotnet publish -c release -o bin/published

# docker build . -t ghosts/client
# docker run -d -p 28085:80 --network ghosts-network --name ghosts-client ghosts/client
# Change network to ghosts-network

FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine

RUN apk add curl && \
    apk add nmap && \
    apk add busybox-extras && \
    apk add nikto && \
    apk add openssh-client && \
    apk add openssh-keygen && \
    apk add python && \
    wget 'https://github.com/sqlmapproject/sqlmap/tarball/master' --output-document=sqlmap.tar.gz && \
    mkdir sqlmap && \
    tar -xvf sqlmap.tar.gz -C sqlmap && \
    cd sqlmap/
    # python sqlmap.py --version


WORKDIR /root/  
COPY  bin/publish .
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000/tcp

CMD ["dotnet", "./ghosts.client.linux.dll"]

# CMD [ "/usr/local/bin/start.sh" ] 
