# Copyright 2017 Carnegie Mellon University. All Rights Reserved. See LICENSE.md file for terms.

# multi-stage target: dev
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev

COPY Ghosts.Api/. /app/Ghosts.Api
COPY Ghosts.Domain/. /app/Ghosts.Domain
COPY Ghosts.Animator/. /app/Ghosts.Animator

WORKDIR /app/Ghosts.Api
RUN dotnet publish -c Release -o /app/dist
COPY Ghosts.Api/config /app/dist/config

CMD ["dotnet", "run"]

# multi-stage target: prod
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS prod
ARG commit
ENV COMMIT=$commit
COPY --from=dev /app/dist /app
WORKDIR /app

LABEL "product"="GHOSTS API"
LABEL "maintainer"="Dustin Updyke <ddupdyke[-@-]sei.cmu.edu>"
LABEL "version"="Browse to /swagger"

EXPOSE 5000
ENV ASPNETCORE_URLS=http://*:5000 \
    ASPNETCORE_ENVIRONMENT=DEVELOPMENT

CMD ["dotnet", "ghosts.api.dll"]
