FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev

# copy csproj and restore as distinct layers
COPY ghosts.client.linux/. /app/
COPY Ghosts.Domain/. /app/Ghosts.Domain/

WORKDIR /app
RUN dotnet restore

# copy everything else and build app
COPY ghosts.client.linux/     ./ghosts.client.linux/
COPY Ghosts.Domain/     ./Ghosts.Domain/
WORKDIR /app/ghosts.client.linux/
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS prod

RUN apk add --no-cache \
    curl \
    nmap \
    busybox-extras \
    nikto \
    openssh-client \
    python3 && \
    wget 'https://github.com/sqlmapproject/sqlmap/tarball/master' -O sqlmap.tar.gz && \
    mkdir sqlmap && \
    tar -xvf sqlmap.tar.gz -C sqlmap && \
    rm sqlmap.tar.gz

COPY --from=dev /app/ghosts.client.linux/out ./app
WORKDIR /app/  

ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000/tcp

CMD ["dotnet", "./ghosts.client.linux.dll"]