name: Build universal binary

on:
  workflow_dispatch:
    branches: [ main ]
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Extract version
      id: version
      run: |
        if [[ $GITHUB_EVENT_NAME == 'release' ]]; then
          echo "version=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        else
          echo "version=latest" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Restore dependencies for Ghosts.Domain
      run: dotnet restore src/Ghosts.Domain/ghosts.domain.csproj

    - name: Restore dependencies for ghosts.client.universal
      run: dotnet restore src/ghosts.client.universal/ghosts.client.universal.csproj

    - name: Build Ghosts.Domain
      run: dotnet build --no-restore src/Ghosts.Domain/ghosts.domain.csproj

    - name: Build ghosts.client.universal
      run: dotnet build --no-restore src/ghosts.client.universal/ghosts.client.universal.csproj --configuration Release -o build_output/

    - name: Zip build output
      run: zip -r ghosts-client-universal-${{ env.version }}.zip build_output/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ghosts-client-universal-${{ env.version }}
        path: ghosts-client-universal-${{ env.version }}.zip
