name: Build universal binary

on:
  workflow_dispatch:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use 'x' to automatically get the latest patch version
    
    - name: Restore dependencies for Ghosts.Domain
      run: dotnet restore src/Ghosts.Domain/ghosts.domain.csproj
    
    - name: Restore dependencies for ghosts.client.universal
      run: dotnet restore src/ghosts.client.universal/ghosts.client.universal.csproj
    
    - name: Build Ghosts.Domain
      run: dotnet build --no-restore src/Ghosts.Domain/ghosts.domain.csproj
    
    - name: Build ghosts.client.universal
      run: dotnet build --no-restore src/ghosts.client.universal/ghosts.client.universal.csproj --configuration Release -o build_output/
      
    - name: Zip build output
      run: zip -r ghosts-client-universal-v8.0.0.zip build_output/
            
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ghosts-client-universal-v8.0.0
        path: ghosts-client-universal-v8.0.0.zip
