name: Create Linux Container

on:
  workflow_dispatch:
    branches: [ main ]
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract tag name # Extract tag name based on event type
        id: tag_name
        run: |
          if [[ $GITHUB_EVENT_NAME == 'release' ]]; then
            echo "tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
          else
            echo "tag=latest" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          tags: |
            dustinupdyke/ghosts-client-linux:${{ env.tag }}
            dustinupdyke/ghosts-client-linux:latest
          push: true
          context: src/.
          file: ./src/Dockerfile-linux-client
